### ISSUE TITLE
Invalid latitudes/longitudes allowed on profile edit

### ISSUE THREAD

**Issue by kiwnix** [fedora-infra/fas#119]
Very large numbers are allowed when latitude should be between -90 and +90 and longitude between -180 and 180.

**Comment by nask0** [comment]
+1

**Comment by ampotty** [comment]
I agree with @kiwnix. I would work on this, but I got a question: I see that latitude and longitude are from the class MaybeFloat, am I able to create two classes? One for latitude and the other for longitude? Regards!

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
