### ISSUE TITLE
czech translation typo on fas user detail page

### ISSUE THREAD

**Issue by covex** [fedora-infra/fas#132]
From fedora webmaster mail:
"
Hi,
there is a typo in czech translation of page title on fas user detail page:
https://admin.fedoraproject.org/accounts/user/view/jdornak

The title is now: "Prohlážet účet", but should be "Prohlížet účet".

Regards,
QB
"
Relevant file:
https://github.com/fedora-infra/fas/blob/develop/po/cs.po

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
