### ISSUE TITLE
Catcha expiration on mobile (iOS Safari)

### ISSUE THREAD

**Issue by spg1502** [fedora-infra/fas#149]
I attempted to create a fedora account using the https://admin.fedoraproject.org/accounts/user/new link and after (slowly) filling out all the forms, I was met with an account creation failure due to the captcha expiring. I attempted to go back to the sign up page and the expired captcha remained.

Providing an option to "refresh" the captcha, or generating a new one when a user navigates back to the filled out form would make the process much easier. In terms of accessibility, it would also make it possible to cycle past a potentially difficult to solve captcha (though that's a very narrow use case).

This would be a QOL fix more than a critical issue, but it may be a good fix for someone new to contributing.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
