### ISSUE TITLE
 Adding Kosovo to the Country List

### ISSUE THREAD

**Issue by ardian** [fedora-infra/fas#154]
Hi there,

I was wondering if we can have Kosovo in the country list, I am not able to choose my country in FAS.

ardian

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
