### ISSUE TITLE
[FAS3] Link to groups using its name

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#166]
Currently links to a group are like: http://0.0.0.0:6543/group/details/154363 it would be nicer if they looked like: http://0.0.0.0:6543/group/details/sysadmin-apprentice

Thoughts?

**Comment by cverna** [comment]
Indeed it would look better . 
If it's decided to go for this, I'd like to work on it

**Comment by pypingou** [comment]
@cverna I'd say go ahead and let's see what @laxathom thinks about it when he sees the code :)

**Comment by sayanchowdhury** [comment]
I am +1 on this thought

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
