### ISSUE TITLE
[FAS3] accessing settings

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#185]
When I go to my profile, I see a link `Settings` in the nav bar at the top, linking to: http://0.0.0.0:6543/settings

I click on it, it asks username/password, entering them does nothing than bringing me back to the page asking for username/password

**Comment by laxathom** [comment]
hm...so if you're seeing the setting link that means you're in the defined admin's group (in config file).
Then, you should be able to go through.
Do you have a log or something, I can't seem to reproduce this issue. That might be related to the data migration.

**Comment by pypingou** [comment]
So I'm seeing in the log
~~~~
2016-07-25 14:37:38,172 DEBUG [waitress:31754][fas:security][validate:498] Granting access
~~~~

But except for a bunch of ``2016-07-25 14:37:38,667 DEBUG [waitress:31754][fas:authentication][_log:51] pyramid.authentication.AuthTktAuthenticationPolicy.authenticated_userid: `` statements, there isn't any interesting log in the console :(

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
