### ISSUE TITLE
[FAS3] Should we show the user in the list of members

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#187]
Currently, if you are a member of the group `foo`, are authenticated and are looking at the detail page for that group, you will not see yourself in the list of members (and the number of members will not reflect your membership [1]).

I found that a little confusing, maybe more people could share their thought on this?

@ryanlerch do you have an opinion on this one?

[1] so if there are 3 persons in that group (including you), the list of members will only show 2 members

**Comment by laxathom** [comment]
This should not looks quite confusing since you can see in the section "membership" your role with all related action allowed (removal, invite, adding, status, etc) so you know you belong to that group avoiding a redundancy.

However, I might not be the more objective person since I know how thing works on this details page.
The idea was more like, I want to see only members of my group, no me but I can understand the lack of accuracy on the total number of members.

**Comment by pypingou** [comment]
Basically I read it as: the membership sections give me my status, but I still kinda expect to see me in the list of members

**Comment by ryanlerch** [comment]
yeah, i agree this should list all the membersof the group. (including yourself)
