### ISSUE TITLE
[FAS3] Accessing a token

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#191]
The value of a token is given when created, but I can't seem to access it after.

So can't I just generate a few tokens one day and install them another day? Can't I find back what access a token has for a known token string?

**Comment by laxathom** [comment]
Well, if you named your token based on your use case, I would say yes. You also has the latest usage next to the token. Also, from your activities page, you can retrieve which client is using it.

No regarding getting back the token api string, but we can think of something like github or other do, as in propose to the user to re-generate the token.

Note that the pop that shows the token api is permanent and only the authenticated user can remove it.

**Comment by pypingou** [comment]
Hm, indeed github doesn't give you back the token string once you've generated it. I find that unfortunate but I can see reasons for it.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
