### ISSUE TITLE
[FAS3] password constraints much lower

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#194]
Compare to FAS2, currently FAS3 has a much lower password policy, we should make sure to fix this

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
