### ISSUE TITLE
[FAS3] Add routes to receive group/users contact info as json

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#197]
In hubs we would like to query fas3 to retrieve group/user info. We can scrape the web page but it might make more sense to retrieve the info as json.

There is a privacy concern but I noticed groups has a bool private column and people has bool privacy column. We can return empty fields if set to private for example

```
return {'email': '', 'irc': ''}
```

**Comment by skrzepto** [comment]
hows this json output for groups?

![selection_046](https://cloud.githubusercontent.com/assets/3166193/17441817/63042de4-5af8-11e6-8c0a-264f550cc238.png)

**Comment by skrzepto** [comment]
I'm working on this branch for this https://github.com/skrzepto/fas/tree/json-info

**Comment by skrzepto** [comment]
Here's the people output
![selection_047](https://cloud.githubusercontent.com/assets/3166193/17444655/c83fedf2-5b06-11e6-9c77-99c2250631d1.png)

**Comment by laxathom** [comment]
Hi @skrzepto , 
FAS comes with a RESTful API already (from a dedicated route). There is no need to provide another route which lead to code duplication and security concern.. 
3rd parties have to use the RESTful API - within the token mechanism in place - in order to retrieve any kind of registered information.

I can understand that you might need more view on the FAS's architecture and available features to drive your contribution. Just lemme know.

**Comment by skrzepto** [comment]
@laxathom could you help me out how to querry FAS3 for the screenshots above? They will be needed for fedora-hubs.

**Comment by laxathom** [comment]
Sure thing.
On your local FAS instance, log in as an admin and go to *settings*'s panel (from the top menu).
From there, you will be able to generate a private token for your 3rd party app. Use the API key from the pop-up to request group info from the RESTful API. 

See https://github.com/fedora-infra/python-fedora/blob/feature/fas3_support/fedora/client/fas2.py for  example on how to talk to fas with a token api.

**Comment by pypingou** [comment]
@laxathom is the API documented somewhere on FAS itself?

**Comment by laxathom** [comment]
Not yet :disappointed: . That's something I need to do.

**Comment by skrzepto** [comment]
@laxathom Need any help writing documentation? I can help.

**Comment by laxathom** [comment]
Hey @skrzepto , for sure any help is welcomed.
Could you give me a couple of time to wrap up a first-start guideline (I use to using sphinx to build docs) so you can continue and add more stuff to it.
I will start with the basis so you can start asap on adding more stuff to it.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
