### ISSUE TITLE
[FAS3] Support registering more than one IRC nick, SSH key, and GPG key per FAS user

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/fas#205]
The current FAS only lets you register one IRC nick per user account. However, I personally use multiple SSH and GPG keys, different IRC nicks from time to time, and it would be great if that information could be represented in FAS.

My [Launchpad account](https://launchpad.net/~ngompa13) represents this information fairly well, but my FAS account does not. I would love it if FAS could represent this information, as I use it way more than my Launchpad account.

**Comment by pypingou** [comment]
You can already have more than one ssh key, just put them one after the other.

**Comment by Conan-Kudo** [comment]
@pypingou After doing that, does it list and let you individually manage those SSH keys?

**Comment by Conan-Kudo** [comment]
@pypingou And that still doesn't address IRC nicks or GPG keys...

**Comment by pypingou** [comment]
>    @pypingou And that still doesn't address IRC nicks or GPG keys...

I didn't say it does :)

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
