### ISSUE TITLE
Add support for ed25519 ssh key

### ISSUE THREAD

**Issue by fdelapena** [fedora-infra/fas#210]
https://fedorahosted.org/fas/ticket/190

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
