### ISSUE TITLE
Suggestion for username / lowercase warning

### ISSUE THREAD

**Issue by bt-003** [fedora-infra/fas#211]
A suggestion was made that when a user logs in and enters his or her user name in upper case, a warning message should be displayed stating that lower case only be used.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
