### ISSUE TITLE
[FAS3] Issue with storing timezone aware in db 

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#212]
Looks like MySQL and SQLite have an issue storing timezone aware times in the db which makes login fail. (related to issue #195 )

Possible solutions
1. Force postgresql only
2.  https://pypi.python.org/pypi/SQLAlchemy-UTCDateTime/

Thoughts or other suggestions?

**Comment by pypingou** [comment]
>  other suggestions?

Use UTC everywhere and don't care about the timezone?

**Comment by skrzepto** [comment]
Technically UTC is a timezone so the issue kind of persists

**Comment by pypingou** [comment]
If all the date/times are using the same timezone, then we do not need to store timezone info, we know they are all in the same timezone.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
