### ISSUE TITLE
[FAS3] Registering a new account crashes

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#217]
I encountered a bug while manually testing registering new accounts. Seems to be related to captcha form being set to none. Anyone else experience this issue?

Steps to reproduce:

1. Go to /register
2. Fill out email, username, pass (everything in the first pane)
3. Leave second pane about irc and bio empty
4. Fill in captcha correctly and click `Sign me up!`
5. Errors right after clicking

Expected Behavior:

To succesfully register the account

Error:

```
AttributeError: 'NoneType' object has no attribute 'validate'
```

**Comment by skrzepto** [comment]
```

File "fas/fas/views/register.py", line 84, in account
if not captchaform.validate() and not la_form.validate():

```

**Comment by skrzepto** [comment]
@laxathom I believe I fixed this in my PR

**Comment by laxathom** [comment]
Oh, can you point me to the change?

**Comment by skrzepto** [comment]
@laxathom https://github.com/fedora-infra/fas/pull/222/files#diff-19f745ebe3eddd44b1a927095bd537a4R122

That PR allows the user to register fine

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
