### ISSUE TITLE
Make client cert optional

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#221]
With the move of the Fedora infrastructure to kerberos for auth with koji, I think it would make sense to make the code to generate/handle client cert optional and configurable in the configuration file.

**Comment by laxathom** [comment]
Client certificates are optional already.
If admins don't add any CA to the system, group's admins won't be able to attach a certificate to a group allowing a member to generate a client certificate.
The option in group edit is only available when there's at least one registered CA.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
