### ISSUE TITLE
[RFE] More nuanced 'active' vs 'inactive' states

### ISSUE THREAD

**Issue by suzannehillman** [fedora-infra/fas#226]
As part of the Fedora Regional Hubs project [1], we have identified a need for increased nuance in people's status in FAS. We would like to be able to provide a filterable master list of people with FAS accounts, and it would be useful to know who is actively involved in Fedora, who is taking a break for whatever reason, who is still available for questions but otherwise inactive, and who no longer wants anything to do with Fedora. Other states may also be useful, but those are the ones which seem most relevant.

I know that there is an 'inactive' state, but because it requires someone to change that state, it is often not up-to-date. 

At the least, it might be helpful to have a general idea of how long it's been since someone used their account. That would at least make it easier to tell that someone may actually be inactive (if they haven't used it in a year). I'm not sure how much can be done in Fedora without logging in, though, so that may be the wrong solution.

[1] https://pagure.io/fedora-hubs/issue/47 and https://pagure.io/fedora-hubs/issue/279

**Comment by ryanlerch** [comment]
We could gauge activity by seeing if the user has generated any messages on the fedmsg queue. If we used this, we would have to exclude some of these, as they can be generated without doing anything (the time since opening a FAS account badge is a good example of this that generates a fedmsg).

As a fallback for people that may be active but dont for some reason generate fedmsgs, we could request that after a year of inactivity on fedmsg that they login to fas to keep the active state.

**Comment by ryanlerch** [comment]
Added the FAS3 label too, as all new features will be implemented there rather than FAS2

**Comment by pypingou** [comment]
Note that FAS2 can give you the date of the last login of a contributor (I hope FAS3 will keep this feature). Since we need to login in FAS to do most of our contributions (except for mailing lists and events, granted), it could be a good starting point.

**Comment by laxathom** [comment]
> As part of the Fedora Regional Hubs project [1], we have identified a need for increased nuance in people's status in FAS. We would like to be able to provide a filterable master list of people with FAS accounts, and it would be useful to know who is actively involved in Fedora [...]

FAS3 brings two kind of activities: account's and group's. So people would be able - based on their level of permission - to have a better view on such thing.

> [..] who is taking a break for whatever reason, [...]

There's a new state called "on vacation" that contributor can set for such thing.

> [...] and who no longer wants anything to do with Fedora. 

Contributors will be able to disable their account themselves

> I know that there is an 'inactive' state, but because it requires someone to change that state, it is often not up-to-date.

FAS3 will bring a tool to do such thing on its own.

>> Note that FAS2 can give you the date of the last login of a contributor (I hope FAS3 will keep this feature). 

You will need to check account's activities now.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
