### ISSUE TITLE
FAS renders poorly on high-DPI screens in Chrome

### ISSUE THREAD

**Issue by lfaraone** [fedora-infra/fas#260]
Visiting https://admin.fedoraproject.org/accounts/ using Google Chrome Version 56.0.2924.76 beta (64-bit) on Debian unstable using a HiDPI display shows me something like this:

![welcome to fas2 - google chrome_027](https://cloud.githubusercontent.com/assets/73410/22620942/8a14d206-eb0f-11e6-90b9-267703814fab.png)

It looks fine on Firefox, and on the same version of Google Chrome on a lower-DPI device.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
