### ISSUE TITLE
Add Nitrokey Pro support

### ISSUE THREAD

**Issue by Germano0** [fedora-infra/fas#261]
As you can read [here](https://plus.google.com/+KonstantinRyabitsev/posts/4a7RNxtt7vy)
> Yubico has replaced all open-source components that made yubikey NEOs so awesome with proprietary closed-source code in Yubikey 4s[...]

So I would like to show you a new alternative: [Nitrokey Pro](https://shop.nitrokey.com/shop/product/nitrokey-pro-3) is an open hardware product that is capable of generating One Time Passwords (and has many other features). It would be great if FAS users can authenticate using such device.
Fedora already has Nitrokey management software in its repository.
[Nitrokey Github](https://github.com/nitrokey)

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
