### ISSUE TITLE
Marking a user as "inactive" or "disabled" doesn't revoke issued certs

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/fas#266]
When a contributor set himself as "inactive" or if an admin marks the user as "disabled" (as we can't really delete it either), it seems that [current] cert issued for that user isn't revoked : 

https://github.com/fedora-infra/fas/blob/master/fas/user.py#L377

So that means also that those certs aren't included in the generated CRL. Is there a way to fix this ? (other than writing a script to query all those informations and revoke "manually" the cert[s])

**Comment by arrfab** [comment]
bump ?

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
