### ISSUE TITLE
Typos in README.rst

### ISSUE THREAD

**Issue by pavankuppa1** [fedora-infra/fas#271]

**Comment by pavankuppa1** [comment]
#272 Fixed typos

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
