### ISSUE TITLE
fasClient --debug -if creates=/var/db/shadow.db should fix permissions on /home/fedora

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/fas#274]
When default Fedora Cloud box is installed nowadays, the /home/fedora directory is owned by fedora:fedora with permissions 0700.  The command though doesn't fix this to 'root:root' and '0755' -> which in turn means that the command itself fails.

**Comment by praiskup** [comment]
Or perhaps move the /home/fedora somewhere (I forgot to tell that `fedora` is the default username on cloud box, where by default - given by cloudinit - the administrator can ssh to).

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
