### ISSUE TITLE
Yubikey FAS OTP - 500 Internal error

### ISSUE THREAD

**Issue by AquaL1te** [fedora-infra/fas#276]
When using the Yubikey option in my [FAS](https://admin.fedoraproject.org/accounts/yubikey/) account, and try a "Test Auth", I get the error "500 Internal error: The server encountered an unexpected condition which prevented it from fulfilling the request."

**Comment by AdamWill** [comment]
Yup. I just hit this today.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
