### ISSUE TITLE
no 2fa on FAS web login

### ISSUE THREAD

**Issue by d-hat** [fedora-infra/fas#282]
As reported by Marcin Zajaczkowski [to infrastructure list](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/TDCCBIUSMNKP77L7S53Q5MFT4YLT4T6J/#TDCCBIUSMNKP77L7S53Q5MFT4YLT4T6J) and confirmed by Stephen Smoogen, the Fedora Account System's 2fa is not yet available for regular users.

This bug is not necessarily to prioritise work on it, but for people who are interested to follow activity or motivated to contribute.

**Comment by pypingou** [comment]
FAS is running on RHEL6 and is no longer being developed. A new portal is being worked on and due to be deployed in Fedora and CentOS in fall 2020 and will have support for 2FA.

You can find out more about it: Probably not, we could just open a ticket for toddler and close this one :)

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against (Noggin)[https://github.com/fedora-infra/noggin]
