### ISSUE TITLE
Add a password tip below login form

### ISSUE THREAD

**Issue by junjieyuan** [fedora-infra/fas#284]
If user setted OTP (2FA), they must using username and password+otp to login.

![fas3-empty-login-form](https://user-images.githubusercontent.com/40716445/113375406-de170380-93a1-11eb-9956-e733b75bbbb3.png)

But some browser, such as Google Chrome, will autofill saved user's username and password to login form. Thus, login form's placeholder has been shadow.

![fas3-autofilled-login-form](https://user-images.githubusercontent.com/40716445/113375412-e2dbb780-93a1-11eb-9657-6d5396aa900d.png)

We should add a tip below login form, there are a example. **It's just a example**.

![fas3-login-form-example](https://user-images.githubusercontent.com/40716445/113375420-e5d6a800-93a1-11eb-9968-28cb2f52a138.png)

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
