### ISSUE TITLE
Add a domain email validation check

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#35]
We should check if domain's email exist and valid before insert/update to database person info.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
