### ISSUE TITLE
Add way to add log comments for admins

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fas#36]
Would be nice for admins to have a way to add comments to an account. In particular when admin locking them.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
