### ISSUE TITLE
highlight or note optional fields when signing up

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fas#37]
See: 
https://lists.fedoraproject.org/pipermail/infrastructure/2013-March/012651.html
In general it would be nice to note when someone is creating a new account what fields are optional or not needed so they can ignore them if they choose to. 

This could be adding (optional) next to those fields, or perhaps putting a \* next to the required fields or something.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
