### ISSUE TITLE
Virtual [user|group] support

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#43]
FAS 3.0 should be able to create virtual user (only by admin or group admin)
- This virtual user [has to|could] be bind to a real user account. it [will|could] also be created based on real user's data as template.
- Why a "virtual user"? virtual user can be a use for system user which has special access/auth where they should not appear from the public user listing even if they have been tagged as "system's user". This way, we can better track to whom this special user belong to and manage its level of permission. Also, this virtual user will be automatically blocked out if the user it's attached to has been set inactive or deleted.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
