### ISSUE TITLE
Shell [environment] customization support

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#45]
IDEA:

Would be nice to allow user to customize their shell or shell's env when they have shell access to server.
Admin would be able to allow what type of shell a group (which allow access to server) can offer and if you can actually customize it for this group you have just been in.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
