### ISSUE TITLE
Require GPG fingerprint instead of key id

### ISSUE THREAD

**Issue by tyll** [fedora-infra/fas#53]
The GPG key id is only a part of the keys fingerprint (at least for current keys) and only the fingerprint properly identifies an keys. Therefore FAS should require fingerprints of users' GPG keys instead of only key ids to be able to do something meaningful with this information. Alternatively users could be allowed to upload a public GPG key.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
