### ISSUE TITLE
Allow multiple GPG keys

### ISSUE THREAD

**Issue by tyll** [fedora-infra/fas#54]
At least one user in FAS wants to specify two GPG key ids, therefore please allow to specify multiple GPG keys, maybe even allow one to be the primary one.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
