### ISSUE TITLE
Please revisit FAS password rules

### ISSUE THREAD

**Issue by comzeradd** [fedora-infra/fas#57]
The requirements for a FAS password are mad, offering no real sense of security. It's better to force long passwords, than forcing into deprecated schemes with special characters, numbers and uppercase letters.

Reference:
https://pbs.twimg.com/media/BhkZoPrCYAEF8ww.png:large
http://xkcd.com/936/

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
