### ISSUE TITLE
Add 2step verification

### ISSUE THREAD

**Issue by cydrobolt** [fedora-infra/fas#73]
I love FAS, but perhaps we could implement 2step verification to the login. One could disable or enable it. If it is enabled on an account, then a `2stepcode` should be passed as a parameter to FAS upon authentication, and should be asked from the user if the user is accessing the page through a browser. 

We could use Google Authenticator (http://stackoverflow.com/questions/8529265/google-authenticator-implementation-in-python, https://code.google.com/p/google-authenticator/)

This is just an idea; if we were to implement it, a lot of work would go into making it work. Ideas appreciated.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
