### ISSUE TITLE
Saving profile form after session times out results in a 500/fatal.

### ISSUE THREAD

**Issue by relrod** [fedora-infra/fas#74]
It should be handled and we should render an error…

**Comment by pypingou** [comment]
Is this still occurring? Was it for FAS2 or FAS3 btw?

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
