### ISSUE TITLE
"0x..." GPG key link indicates a non-graceful failure upon visiting

### ISSUE THREAD

**Issue by jnpkrn** [fedora-infra/fas#79]
Used to have the key set starting with 0x, got some error on visiting the link.  I noticed the hint indicates it's not supported.  Might be better if either the link wasn't active in that case or the link formatter managed to cope with that.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
