### ISSUE TITLE
License Agreement's management

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#81]
Create and delete licenses from settings' page.

License can't be deleted if attached to any of  registered groups.
Pop up a dialog about it and request some action before be able to delete
selected group.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
