### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#94]
Use as backend for People and Groups.

We still are gonna use the db for everything else which mean,
feature should be done without having to change high level code which do
requests to People and Groups' objects.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
