### ISSUE TITLE
[connected apps] twitter

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#95]
Contributors would be able to connect their Fedora account to twitter which will
allow them to share any events from Fedora services (builds, pkgs updates, badges, etc)

**Comment by dustymabe** [comment]
I'd like an option in FAS to add twitter ID - not necessarily to link your account to twitter but just so the information is available if people want to share it. 

my idea here is to create a cool little app that will monitor fedmsg and tweet out when someone gets a new badge. It will be easier to do this if there is a spot in FAS that allows one to specify their twitter handle.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
