### ISSUE TITLE
Create a requirements file

### ISSUE THREAD

**Issue by cydrobolt** [fedora-infra/fas#96]
A `requirements.txt` would be very helpful. It was really annoying to find the needed dependencies, since they were not clearly listed or provided in a requirements file.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
